
function(ADD_EXAMPLE NAME SOURCE)
    add_executable(flux.example.${NAME} ${SOURCE})
    target_link_libraries(flux.example.${NAME} flux::flux)
    if(${${NAME}_SKIP_TEST})
      #pass
    else()
      add_test(NAME ${NAME} COMMAND flux.example.${NAME} ${${NAME}_ARGS})
    endif()
endfunction()

add_example(config_parser config_parser.cpp)
add_example(calendar calendar.cpp)
add_example(merge_intervals merge_intervals.cpp)
add_example(histogram histogram.cpp)
set(example-word-count_SKIP_TEST ON)
add_example(word_count word_count.cpp)
add_example(prime_numbers prime_numbers.cpp)
add_example(shortest_path shortest_path.cpp)
add_example(moving_average moving_average.cpp)

add_example(docs.adjacent docs/adjacent.cpp)
add_example(docs.adjacent-filter docs/adjacent_filter.cpp)
add_example(docs.all docs/all.cpp)
add_example(docs.any docs/any.cpp)
add_example(docs.cartesian_power docs/cartesian_power.cpp)
add_example(docs.cartesian_power_map docs/cartesian_power_map.cpp)
add_example(docs.cartesian_product docs/cartesian_product.cpp)
add_example(docs.cartesian_product_map docs/cartesian_product_map.cpp)
add_example(docs.compare docs/compare.cpp)
add_example(docs.contains docs/contains.cpp)
add_example(docs.count docs/count.cpp)
add_example(docs.cursors docs/cursors.cpp)
add_example(docs.cycle docs/cycle.cpp)
add_example(docs.drop docs/drop.cpp)
add_example(docs.ends_with docs/ends_with.cpp)
add_example(docs.find_max docs/find_max.cpp)
add_example(docs.find_min docs/find_min.cpp)
add_example(docs.find_minmax docs/find_minmax.cpp)
add_example(docs.mask docs/mask.cpp)
add_example(docs.prescan docs/prescan.cpp)
add_example(docs.read_only docs/read_only.cpp)
add_example(docs.repeat docs/repeat.cpp)
add_example(docs.scan docs/scan.cpp)
add_example(docs.set_difference docs/set_difference.cpp)
add_example(docs.set_intersection docs/set_intersection.cpp)
add_example(docs.set_symmetric-difference docs/set_symmetric_difference.cpp)
add_example(docs.set_union docs/set_union.cpp)
add_example(docs.scan_first docs/scan_first.cpp)
add_example(docs.split docs/split.cpp)
add_example(docs.starts_with docs/starts_with.cpp)
add_example(docs.unfold docs/unfold.cpp)

add_example(top10.01_trapping_rain_water top10/01_trapping_rain_water.cpp)
add_example(top10.02_max_consecutive_ones top10/02_max_consecutive_ones.cpp)
add_example(top10.03_longest_continuous_increasing_subsequence top10/03_longest_continuous_increasing_subsequence.cpp)
add_example(top10.04_maximum_subarray_sum top10/04_maximum_subarray_sum.cpp)
add_example(top10.05_sushi_for_two top10/05_sushi_for_two.cpp)
add_example(top10.06_max-gap top10/06_max_gap.cpp)
add_example(top10.07_max-gap-count top10/07_max_gap_count.cpp)
add_example(top10.08_three_consecutive_odds top10/08_three_consecutive_odds.cpp)
add_example(top10.09_skyline top10/09_skyline.cpp)
add_example(top10.10_ocean_view top10/10_ocean_view.cpp)

