# Based on macos.yml from {fmt}
# https://github.com/fmtlib/fmt/blob/master/.github/workflows/macos.yml

name: MacOS CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  CXXFLAGS: -Wall -Wextra -Wconversion -Wsign-conversion -pedantic -fno-omit-frame-pointer

jobs:
  build:
    runs-on: macos-26
    strategy:
      matrix:
        compiler: [AppleClang, LLVM-Clang-19, LLVM-Clang-20, LLVM-Clang-21, LLVM-Clang-22, LLVM-Clang-23]
        test_with: [Headers, Module]
        build_type: [Debug, Release]

        exclude:
          - compiler: AppleClang
            test_with: Module
          - compiler: LLVM-Clang-19
            test_with: Module

        include:
          - compiler: AppleClang
            cxx: clang++
          - compiler: LLVM-Clang-19
            cxx: $(brew --prefix llvm@19)/bin/clang++
            install: |
              brew install llvm@19
          - compiler: LLVM-Clang-20
            cxx: $(brew --prefix llvm@20)/bin/clang++
            install: |
              brew install llvm@20
          - compiler: LLVM-Clang-21
            cxx: $(brew --prefix llvm@21)/bin/clang++
            ldflags: -L$(brew --prefix llvm@21)/lib/c++
            install: |
              brew install llvm@21
          - compiler: LLVM-Clang-22
            cxx: $(brew --prefix llvm@22)/bin/clang++
            ldflags: -L$(brew --prefix llvm@22)/lib/c++
            install: |
              brew install llvm@22
          - compiler: LLVM-Clang-23
            cxx: $(brew --prefix llvm@23)/bin/clang++
            ldflags: -L$(brew --prefix llvm@23)/lib/c++
            install: |
              brew install llvm@23

    steps:
    - uses: actions/checkout@master

    - name: Create Build Environment
      run: |
        ${{matrix.install}}

    - name: Configure
      run: |
        cmake -B build -GNinja \
              -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
              -DCMAKE_CXX_COMPILER=${{matrix.cxx}} \
              -DCMAKE_EXE_LINKER_FLAGS=${{matrix.ldflags}} \
              -DCMAKE_OSX_SYSROOT=$(xcrun --sdk macosx --show-sdk-path) \
              -DCMAKE_CXX_EXTENSIONS=Off \
              -DFLUX_BUILD_BENCHMARKS=${{matrix.build_type == 'Release'}} \
              -DFLUX_BUILD_MODULE=${{matrix.test_with == 'Module'}}

    - name: Build
      run: cmake --build build --config ${{matrix.build_type}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.build_type}}
      env:
        CTEST_OUTPUT_ON_FAILURE: True
